baseURL = 'https://theofbraune.github.io/blog'
DefaultContentLanguage = "en"
title = 'Theo Braune'
defaultContentLanguageInSubdir = false
relativeURLs = true
pathPrefix = 'blog'

paginate =30

[params]
dateFormat = "Jan 2, 2006, 3:04PM"


