baseURL = 'https://theofbraune.github.io/'
DefaultContentLanguage = "en"
title = 'Maths of Glory'
defaultContentLanguageInSubdir = true
relativeURLs = true

paginate =8

[params]
dateFormat = "Jan 2, 2006, 3:04PM"


